import * as THREE from "three";
import type { LandscapeObject, PropertyConfig } from "../../types/landscape";

export async function exportObj(
  objects: LandscapeObject[],
  property: PropertyConfig,
  filename: string
): Promise<void> {
  const { buildScene } = await import("./buildScene");
  const { OBJExporter } = await import(
    "three/examples/jsm/exporters/OBJExporter.js"
  );

  const scene = buildScene(objects, property);
  const exporter = new OBJExporter();
  const objString = exporter.parse(scene);

  // Generate MTL from scene materials
  const mtlString = generateMtl(scene);

  // Prepend mtllib reference to OBJ
  const objWithMtl = `mtllib ${filename}.mtl\n${objString}`;

  downloadText(objWithMtl, `${filename}.obj`);
  // Small delay so browser doesn't merge downloads
  await new Promise((r) => setTimeout(r, 200));
  downloadText(mtlString, `${filename}.mtl`);
}

function generateMtl(scene: THREE.Scene): string {
  const seen = new Set<string>();
  const lines: string[] = ["# Generated by Gradient"];

  scene.traverse((node) => {
    if (!(node instanceof THREE.Mesh)) return;
    const mat = node.material as THREE.MeshStandardMaterial;
    if (!mat || !mat.name || seen.has(mat.name)) return;
    // OBJExporter assigns material names; use those
    seen.add(mat.name);

    const c = mat.color;
    lines.push("");
    lines.push(`newmtl ${mat.name}`);
    lines.push(`Kd ${c.r.toFixed(4)} ${c.g.toFixed(4)} ${c.b.toFixed(4)}`);
    lines.push(`d ${mat.opacity.toFixed(4)}`);
    lines.push(`Ns ${((1 - mat.roughness) * 100).toFixed(1)}`);
    lines.push("illum 2");
  });

  return lines.join("\n");
}

function downloadText(content: string, name: string): void {
  const blob = new Blob([content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = name;
  a.click();
  URL.revokeObjectURL(url);
}
